#!/usr/bin/env bash
# A script to display subdomain information
if [ "$2" ]
then
	dig "$2.$1" | awk -v sub_="$2" '/ANSWER SECTION:/ {getline; printf "The subdomain %s is a %s record and points to %s\n", sub_, $4, $5}'
else
	dig www."$1" | awk '/ANSWER SECTION:/ {getline; printf "The subdomain www is a %s record and points to %s\n", $4, $5}'
	dig lb-01."$1" | awk '/ANSWER SECTION:/ {getline; printf "The subdomain lb-01 is a %s record and points to %s\n", $4, $5}'
	dig web-01."$1" | awk '/ANSWER SECTION:/ {getline; printf "The subdomain web-01 is a %s record and points to %s\n", $4, $5}'
	dig web-02."$1" | awk '/ANSWER SECTION:/ {getline; printf "The subdomain web-02 is a %s record and points to %s\n", $4, $5}'
fi
