#!/usr/bin/env bash
# Install and configure a nginx server

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Update html index page
sudo chmod 777 /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html

# Add 301 permanent remove
sudo sed -i "38i\ \tlocation /redirect_me {\n\t\treturn 301 https://google.com;\n\t}\n" /etc/nginx/sites-enabled/default

# Add 404 page
sudo touch /usr/share/nginx/html/404.html
sudo chmod 777 /usr/share/nginx/html/404.html
echo -e "Ceci n'est pas une page\n" > /usr/share/nginx/html/404.html
change="#error_page 404"
new="error_page 404"
sudo sed -i "s/$change/$new/" /etc/nginx/sites-enabled/default

# Add custom http header
sudo sed -i "21i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restart server
sudo service nginx restart
