#!/usr/bin/env bash
# This script prints number 1 to 10 and lists bad luck numbers

i=1
while [ $i -le 20 ] 
do
	echo "$i"
	if [ $i == 4 ]
	then
		echo "back luck from China"
	elif [ $i == 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i == 17 ]
	then
		echo "bad luck from Italy"
	fi
	let i=i+1
done
