#!/usr/bin/env bash
# Running server as user nginx and listen to port 80
sed -i "5i\ user nginx;\n" /etc/nginx/nginx.conf
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
pkill apache2
chown nginx:nginx /etc/nginx/nginx/conf
chown nginx:nginx /var/log/nginx  
chown nginx:nginx /var/run/nginx.pid
sudo -u nginx service nginx restart
